### PR TITLE
Update site-navigation.js

### PR DESCRIPTION
**Pull request by heathergreerklein**
Replace "what is samvera" in top menu with "why use samvera" and remove the existing "why use samvera" menu item.

### CODE REVIEW

**Comment by heathergreerklein** [comment]
@adamjarling I thought I might be able to do this myself, but it doesn't look like it worked. If there is something else I need to change, I'm happy to learn it!

**Comment by adamjarling** [comment]
@heathergreerklein Hmmm, that should have just worked.  I'll take a look.

**Comment by adamjarling** [comment]
@heathergreerklein Ah, yea that file `site-navigation.js` is automatically built based on the directory structure in the `/markdown` folder when the app builds in Github.  It's referenced [here](https://github.com/samvera/samvera.org#build-site-navigation) but I should be more explicit about it and put a comment in the code saying "This is automatically built, do not update directly".

So maybe we can group up on what you're trying to do so I can understand better?  Currently there already exists a `/markdown/why-use-samvera` folder, which is going to drive the navigation.  Are you trying to get rid of the "What is Samvera" top nav link?   

If you're just trying to rename, then maybe the solution is renaming the existing 'why-use-samvera' folders to something new.  And then rename the `what-is-samvera` folder to `why-use-samvera`.   Probably easiest to just chat through it.

**Comment by heathergreerklein** [comment]
Thank you Adam! I think that is exactly the info I needed. I'm going to try something and then I'll schedule time with you if I can't make it work.

**Pull request merged**
